version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ${HOME}/jellyfin/config:/config
      - ${HOME}/jellyfin/cache:/cache
      - ${HOME}/jellyfin/media:/media
      - ${HOME}/jellyfin/media2:/media2:ro
    restart: 'no'
    extra_hosts:
      - "host.docker.internal:host-gateway"