version: '3.5'
services:
  jellyfin:
    image: 'jellyfin/jellyfin:10.8.10'
    container_name: jellyfin
    ports:
      - '8096:8096'
      - '8920:8920'
    volumes:
      - ${HOME}/jellyfin/config:/config
      - ${HOME}/jellyfin/cache:/cache
      - ${HOME}/jellyfin/media:/media
      - ${HOME}/jellyfin/media2:/media2:ro
    restart: 'unless-stopped'